# Generated by Django 4.1.5 on 2023-02-16 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PB', 'Published'), ('DT', 'Draft')], default='PB', max_length=2)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date_published'], name='blog_post_date_pu_35a13c_idx'),
        ),
    ]
